### ISSUE TITLE
api.ai Agent files for your Tasks repo

### ISSUE THREAD

**Issue by xVir** [xVir/tasks#1]
quote:

abaker from Tasks repo redirected me to you -
"Check out https://github.com/xVir/tasks, I believe this is the work that the youtube demo was based off of"
I think the issues in that repo are disabled, so am trying to reach out to you through this.

I am getting started with Api.ai and wanted to play around with the Tasks example. I am trying to emulate a similar thing for a Hybrid app. 
I looked through the code base and couldn't find any reference to the API.AI
(I came here through https://www.youtube.com/watch?v=kz_xCEPNJGw)

Can you help me in getting the agent for the api.ai which I can import in the UI and try it out?

Thanks a lot.

cc: @kshitizshankar

**Comment by xVir** [comment]
@kshitizshankar for sample code please take a look at the `ApiAiTasksAgent` class 
https://github.com/xVir/tasks/blob/master/src/main/java/com/todoroo/astrid/voice/ApiAiTasksAgent.java

and it usage in the `TaskListActivity` class
https://github.com/xVir/tasks/blob/master/src/main/java/com/todoroo/astrid/activity/TaskListActivity.java

**Comment by kshitizshankar** [comment]
@xVir I am building an hybrid app (not too familiar with Java). Are there any agent files (the ones that can be exported from the API.AI platform and imported back?)

**Comment by xVir** [comment]
Hi, @kshitizshankar,
did you mean sample agent for Tasks?

**Comment by kshitizshankar** [comment]
Yeah... the one which is shown in the video that i mentioned before..

**Comment by xVir** [comment]
@kshitizshankar please take a look at this 
https://www.dropbox.com/s/2ja42yx5nyy50t3/Tasks.zip?dl=0

**Comment by xVir** [comment]
I think, this should help. Import it to your api.ai agent

**Comment by kshitizshankar** [comment]
@xVir Awesome! Thanks a lot. Would help me in getting started with API.AI :)

**Comment by xVir** [comment]
@kshitizshankar you are welcome! :+1:

**Comment by yadidl** [comment]
@xVir 
can you please upload the tasks zip again ?

**Comment by xVir** [comment]
Hi, @yadidl 
Please try this:
[tasks3.zip](https://github.com/xVir/tasks/files/820398/tasks3.zip)

Thanks!

**Comment by yadidl** [comment]
Thanks!
